Covid Vaccination

In [88]:
import csv
with open('country_vaccinations.csv') as File:
    reader = csv.DictReader(File)
    #for row in reader:
    #    print(row);
    File.close()

In [60]:
import pandas as pd
from matplotlib import pyplot as plt

data=pd.read_csv('country_vaccinations.csv')
data

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15339,Zimbabwe,ZWE,2021-04-30,500342.0,414735.0,85607.0,22745.0,19194.0,3.37,2.79,0.58,1291.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15340,Zimbabwe,ZWE,2021-05-01,520299.0,428135.0,92164.0,19957.0,21171.0,3.50,2.88,0.62,1424.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15341,Zimbabwe,ZWE,2021-05-02,524199.0,430068.0,94131.0,3900.0,19169.0,3.53,2.89,0.63,1290.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15342,Zimbabwe,ZWE,2021-05-03,537516.0,437751.0,99765.0,13317.0,17987.0,3.62,2.95,0.67,1210.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15343,Zimbabwe,ZWE,2021-05-04,559777.0,452191.0,107586.0,22261.0,17977.0,3.77,3.04,0.72,1210.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...

In [87]:
#country_list = pd.unique(data['country'])
#country_list

1, The top10 country with most Vaccination Percentage
2, The top10 country with least Vaccination Percentage
3, The top10 country with most Daily Vaccination Rate
4, The top10 country with least Daily Vaccination Rate
5, Stand Distribution of Vaccination Percentage

1, The top10 country with most Vaccination Percentage

In [85]:

df = pd.DataFrame(data)
df.loc[:,['country', 'total_vaccinations_per_hundred']].groupby('country').max().sort_values(by="total_vaccinations_per_hundred",ascending=False).head(10)

                      total_vaccinations_per_hundred
country
Gibraltar                                     211.08
Seychelles                                    129.88
Falkland Islands                              126.53
Israel                                        121.03
United Arab Emirates                          108.99
Cayman Islands                                 99.96
Bermuda                                        89.77
San Marino                                     88.22
Isle of Man                                    86.40
Jersey                                         84.20

2, The top10 country with least Vaccination Percentage

In [95]:
df = pd.DataFrame(data)
df.loc[:,['country', 'total_vaccinations_per_hundred']].groupby('country').max().sort_values(by="total_vaccinations_per_hundred",ascending=True).head(10)

                              total_vaccinations_per_hundred
country
Cameroon                                                0.00
Democratic Republic of Congo                            0.00
South Sudan                                             0.01
Niger                                                   0.01
Libya                                                   0.01
Syria                                                   0.01
Armenia                                                 0.02
Papua New Guinea                                        0.03
Mauritania                                              0.15
Algeria                                                 0.17

3, The top10 country with most Daily Vaccination Rate

In [96]:

df = pd.DataFrame(data)
df.loc[:,['country', 'daily_vaccinations_per_million']].groupby('country').max().sort_values(by="daily_vaccinations_per_million",ascending=False).head(10)

                  daily_vaccinations_per_million
country
Bhutan                                  118759.0
Falkland Islands                         54264.0
Gibraltar                                31700.0
Mongolia                                 28519.0
Seychelles                               24415.0
Aruba                                    23350.0
Anguilla                                 22064.0
Israel                                   21366.0
Curacao                                  21036.0
San Marino                               20950.0

4, The top10 country with least Daily Vaccination Rate

In [97]:
df = pd.DataFrame(data)
df.loc[:,['country', 'daily_vaccinations_per_million']].groupby('country').max().sort_values(by="daily_vaccinations_per_million",ascending=True).head(10)

                              daily_vaccinations_per_million
country
Niger                                                    3.0
Democratic Republic of Congo                             3.0
Syria                                                    4.0
South Sudan                                              8.0
Cameroon                                                15.0
Papua New Guinea                                        15.0
Bosnia and Herzegovina                                  80.0
Algeria                                                 85.0
Mauritania                                              88.0
Taiwan                                                 118.0

5, Stand Distribution of Vaccination Percentage

In [94]:
(df.loc[:,['country', 'total_vaccinations_per_hundred']].groupby('country').max())['total_vaccinations_per_hundred'].std()

31.494854748731093

In [98]:
(df.loc[:,['country', 'total_vaccinations_per_hundred']].groupby('country').max())['total_vaccinations_per_hundred'].mean()

24.175025641025666